### ISSUE TITLE
Robotic Arm lateral shift - error in sign depending on patient orientation

### ISSUE THREAD

**Issue by lukejamesmurray** [mghro/rad-collision#17]
The geometry for the 2 arms do not line up.
Seems like one of the arms might be going in the opposite direction it is supposed to.

**Comment by ferdymercury** [comment]
Thanks for the hint.

In this video, they do line up. https://www.youtube.com/watch?v=6osJI_xftAE

So it might be a problem with the fact that in the video, the patient orientation is FFS.

In your case, is the patient orientation HFS ?

You could try to change the sign here https://github.com/mghro/rad-collision/blob/master/collision_detection.py#L1191 for your orientation.

**Comment by lukejamesmurray** [comment]
> You could try to change the sign here https://github.com/mghro/rad-collision/blob/master/collision_detection.py#L1191 for your orientation.

Hey, I've tried that and it still happens.
Is it not going to be some of the logic around line 1402? 
As it is more about how the 2 robotic arms move, rather than the couch itself.

Thanks

**Comment by ferdymercury** [comment]
Thanks for checking.

Does it happen already when loading the script, or later on when moving the sliders?

**Comment by lukejamesmurray** [comment]
The initial position is fine, they are both tucked under the couch aligned on top of each other.
As soon as the slider is touched, they start to separate.

Might be some math with the bangle/tangle?

**Comment by ferdymercury** [comment]
Mmm not sure. What happens if you remove the minus sign in https://github.com/mghro/rad-collision/blob/master/collision_detection.py#L966 ?

**Comment by lukejamesmurray** [comment]
hmm no luck. 

The uppermost arm behaves as it should, the lower arm is the only one that suddenly shifts, it doesnt seem to have an anchor point. (it totally moves in space)

**Comment by ferdymercury** [comment]
I was able to reproduce the problem.

- It works with FFS orientation
- It fails with FFP orientation.

**Comment by ferdymercury** [comment]
I have commited a fix. Please let me know if it works for you now. Thanks!

**Comment by ferdymercury** [comment]
I see the issue now, I will look at it.

**Comment by ferdymercury** [comment]
I think I solved it now. Attached are some (crappy) handnotes for (my) the record.
[robot_arm_maths.pdf](https://github.com/mghro/rad-collision/files/5247309/robot_arm_maths.pdf)

**Comment by ferdymercury** [comment]
@lukejamesmurray confirms HFS and HFP patients work on his side, too.
