### ISSUE TITLE
Suggestion: Issue template to request some basic details?

### ISSUE THREAD

**Issue by jmartens** [mghro/rad-collision#19]
Would it be an idea to setup a simple issue template for new issues to query some data from the user, for example RayStation version as well as perhaps a traceback when available?

I think this could give you valuable information.

More on issue templates can be found at https://docs.github.com/en/github/building-a-strong-community/configuring-issue-templates-for-your-repository

**Comment by ferdymercury** [comment]
Thanks for the suggestion. Added now.
